version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/clean_up.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
    - location: scripts/setup_nginx.sh
      timeout: 300
      runas: ubuntu
  AplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  
