version: 0.2

env:
  secrets-manager:
    DB_USERNAME: "coby-app/db-credentials:DB_USERNAME"
    DB_PASSWORD: "coby-app/db-credentials:DB_PASSWORD"
    GOOGLE_CLIENT_ID: "coby-app/db-credentials:GOOGLE_CLIENT_ID"
    GOOGLE_CLIENT_SECRET: "coby-app/db-credentials:GOOGLE_CLIENT_SECRET"
    KAKAO_CLIENT_ID: "coby-app/db-credentials:KAKAO_CLIENT_ID"

phases:
  install:
    runtime-versions:
      nodejs: 20
      java: corretto17

  pre_build:
    commands:
      - echo "ðŸ“¦ í”„ë¡ íŠ¸ì—”ë“œ ì˜ì¡´ì„± ì„¤ì¹˜"
      - cd frontend
      - npm install
      - cd ..

  build:
    commands:
      - echo "ðŸ› ï¸ í”„ë¡ íŠ¸ì—”ë“œ ë¹Œë“œ"
      - cd frontend
      - npm run build
      - cd ..

      - echo "ðŸ› ï¸ ë°±ì—”ë“œ Gradle ë¹Œë“œ"
      - cd backend
      - chmod +x ./gradlew
      - ./gradlew build -x test
      - cd ..

  post_build:
    commands:
      - mkdir -p build_output/scripts
      - mkdir -p build_output/frontend
      - mkdir -p build_output/backend
      - mv frontend/build build_output/frontend
      - mv backend/build/libs/*.jar build_output/backend
      - cp appspec.yml build_output/
      - cp -r scripts build_output/
      - echo "export DB_USERNAME=${DB_USERNAME}" >> build_output/scripts/env.sh
      - echo "export DB_PASSWORD=${DB_PASSWORD}" >> build_output/scripts/env.sh
      - echo "export GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}" >> build_output/scripts/env.sh
      - echo "export GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}" >> build_output/scripts/env.sh
      - echo "export KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}" >> build_output/scripts/env.sh
      - chmod +x build_output/scripts/*.sh


artifacts:
  base-directory: build_output
  files:
    - '**/*'
