version: 0.2

env:
  secret-manager:
    DB_URL: "coby-app/db-credentials:DB_URL"
    DB_USERNAME: "coby-app/db-credentials:DB_USERNAME"
    DB_PASSWORD: "coby-app/db-credentials:DB_PASSWORD"

phases:
  install:
    runtime-versions:
      nodejs: 20
      java: corretto17
    commands:
      - echo "Installing dependencies"
      - echo "Current directory: $(pwd)"
      - ls -al

  pre_build:
    commands:
      - echo "Starting pre-build phase"
      - cd frontend
      - npm install
      - cd ..

  build:
    commands:
      - echo "Starting build process"
      - echo "Building React frontend"
      - cd frontend
      - npm run build
      - cd ..
      - echo "Building SpringBoot backend"
      - cd backend
      - chmod +x ./gradlew
      - ./gradlew build -x test
      - cd ..

  post_build:
    commands:
      - echo "Build Completed. Preparing artifact"
      - mkdir -p build_output/frontend
      - mkdir -p build_output/backend
      - echo "== 현재 위치: $(pwd) =="
      - ls -al ./frontend || echo "❌ frontend 폴더가 없습니다!"
      - ls -al ./frontend/build || echo "❌ frontend/build 폴더가 없습니다!"
      - mv ./frontend/build ./build_output/frontend || echo "⚠️ React 빌드 결과 복사 실패"
      - mv ./backend/build/libs/*.jar ./build_output/backend || echo "⚠️ 백엔드 JAR 복사 실패"
      - cp ./appspec.yml ./build_output/
      - cp -r ./scripts ./build_output/

artifacts:
  files:
    - '**/*'
  base-directory: build_output
