version: 0.2
env:
  secret-manager:
    DB_URL:       "coby-app/db-credentials:DB_URL"
    DB_USERNAME:  "coby-app/db-credentials:DB_USERNAME"
    DB_PASSWORD:  "coby-app/db-credentials:DB_PASSWORD"
phases:
  install:
    ...
  pre_build:
    ...
  build:
    ...
  post_build:
    commands:
      - echo "Build Completed. Preparing artifact"

      # ① build_output/scripts 디렉터리 확보
      - mkdir -p build_output/scripts

      # ② start_server.sh · stop_server.sh … 복사
      - cp scripts/*.sh build_output/scripts/

      # ③ **여기서 env.sh를 새로 생성**  (Secrets Manager 값 사용)
      - cat <<EOF > build_output/scripts/env.sh
        export DB_USERNAME=${DB_USERNAME}
        export DB_PASSWORD=${DB_PASSWORD}
        export GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
        export GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
        export KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
        EOF
      - chmod +x build_output/scripts/*.sh

artifacts:
  base-directory: build_output       # ← 그대로
  files:
    - '**/*'                         # build_output 아래 전부
