
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Check AWS identity
        run: aws sts get-caller-identity

      - name: Start CodePipeline
        run: aws codepipeline start-pipeline-execution --name coby-pipeline

      - name: Zip source code
        run: zip -r source.zip .

      - name: Upload to S3
        run: aws s3 cp source.zip s3://coby-ci-cd-s3/source.zip

      - name: Start CodePipeline
        run: aws codepipeline start-pipeline-execution --name coby-pipeline
